title: pixel-art-unplugged
hero_image: images/banner.png
description: pixel-art-unplugged description
version: 4
listed: false
copyedit: false
last_tested: "2019-02-05"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
