title: Create pixel art
hero_image: images/banner.png
description: An unplugged activity for creating pixel art
version: 4.1
listed: false
copyedit: true
last_tested: "2019-04-16"
steps:
  - title: Introduction
  - title: Pixels
  - title: "Challenge: decode a bigger picture"
    challenge: true
  - title: Create your own pixel art
  - title: Encode your picture
  - title: "Challenge: create a multicolour picture"
    challenge: true
  - title: What next?
